use wow_adt::Adt;

use base64::{engine::general_purpose, Engine as _};
use flate2::{write::DeflateEncoder, Compression};

use std::collections::BTreeMap;
use std::fs::{self, File};
use std::io::{Cursor, Write};
use std::path::{Path, PathBuf};

/// Root ADT filename parser.
/// Accepts: "<map>_<x>_<y>.adt"
/// Rejects: "<map>_<x>_<y>_obj0.adt", "_tex0.adt", "_lod.adt", etc.
fn parse_root_adt_filename(path: &Path) -> Option<(String, u32, u32)> {
    if path.extension()?.to_str()?.to_ascii_lowercase() != "adt" {
        return None;
    }
    let stem = path.file_stem()?.to_str()?.to_string(); // no ".adt"
    let parts: Vec<&str> = stem.split('_').collect();
    if parts.len() != 3 {
        // root ADT is exactly 3 parts: name_x_y
        return None;
    }
    let map = parts[0].to_string();
    let x: u32 = parts[1].parse().ok()?;
    let y: u32 = parts[2].parse().ok()?;
    Some((map, x, y))
}

fn tile_key(tile_x: u32, tile_y: u32) -> u32 {
    // stable compact key for Lua table
    tile_y * 64 + tile_x
}

/// Pack 256 u32 areaIDs into 1024 bytes LE, deflate, base64.
fn encode_tile_deflate_b64(area_ids_256: &[u32]) -> Result<String, Box<dyn std::error::Error>> {
    if area_ids_256.len() != 256 {
        return Err(format!("expected 256 area IDs, got {}", area_ids_256.len()).into());
    }

    let mut raw = Vec::with_capacity(256 * 4);
    for &v in area_ids_256 {
        raw.extend_from_slice(&v.to_le_bytes());
    }

    let mut enc = DeflateEncoder::new(Vec::new(), Compression::best());
    enc.write_all(&raw)?;
    let compressed = enc.finish()?;

    Ok(general_purpose::STANDARD.encode(compressed))
}

/// Parse a single root ADT and return 256 area IDs (16x16 chunks).
/// Pads with 0s if fewer than 256 chunks, skips if no chunks at all.
fn parse_adt_areaids(path: &Path) -> Result<Option<Vec<u32>>, Box<dyn std::error::Error>> {
    let data = fs::read(path)?;
    let adt = Adt::from_reader(Cursor::new(data))?;

    // wow_adt exposes chunk.area_id for MCNK chunks
    let mut area_ids: Vec<u32> = adt
        .mcnk_chunks
        .iter()
        .map(|chunk| chunk.area_id)
        .collect();

    let chunk_count = area_ids.len();
    
    if chunk_count == 0 {
        // Truly empty tile, skip
        return Ok(None);
    }
    
    if chunk_count != 256 {
        println!("    note: {} has {} chunks (expected 256), padding with zeros", 
                 path.file_name().unwrap_or_default().to_string_lossy(), chunk_count);
        // Pad to 256 with zeros
        area_ids.resize(256, 0);
    }

    Ok(Some(area_ids))
}

/// Per-tile grid export container
pub struct TileGridExport {
    pub continent_name: String,
    /// tileKey -> base64(deflate(raw 1024 bytes of u32 LE areaids))
    pub tiles: BTreeMap<u32, String>,
}

impl TileGridExport {
    pub fn new(continent_name: &str) -> Self {
        Self {
            continent_name: continent_name.to_string(),
            tiles: BTreeMap::new(),
        }
    }

    pub fn export_lua(&self, out_path: &Path) -> std::io::Result<()> {
        let mut f = File::create(out_path)?;

        writeln!(f, "-- Auto-generated per-tile AreaID grid for {}", self.continent_name)?;
        writeln!(f, "-- Each tile is 16x16 chunks (256 u32 AreaIDs).")?;
        writeln!(f, "-- Stored as: base64(deflate(raw_bytes)), where raw_bytes = 256 * u32 little-endian (1024 bytes).")?;
        writeln!(f, "-- Generated by zone-map Rust tool")?;
        writeln!(f)?;
        writeln!(f, "local _, addon = ...")?;
        writeln!(f)?;
        writeln!(f, "local tiles = {{")?;

        // Keep lines reasonable length
        for (k, v) in &self.tiles {
            writeln!(f, "  [{}] = [[{}]],", k, v)?;
        }

        writeln!(f, "}}")?;
        writeln!(f)?;
        writeln!(f, "addon:RegisterTileGrid(\"{}\", {{", self.continent_name)?;
        writeln!(f, "  name = \"{}\",", self.continent_name)?;
        writeln!(f, "  tileSize = 16,")?;
        writeln!(f, "  tilesPerSide = 64,")?;
        writeln!(f, "  tiles = tiles,")?;
        writeln!(f, "}})")?;
        Ok(())
    }
}

fn build_tile_export(adt_dir: &Path, continent_name: &str) -> Result<TileGridExport, Box<dyn std::error::Error>> {
    let mut export = TileGridExport::new(continent_name);

    let mut parsed = 0usize;
    let mut skipped = 0usize;
    let mut errors = 0usize;

    println!("Scanning ADT dir: {}", adt_dir.display());

    for entry in fs::read_dir(adt_dir)? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }

        let Some((map_name, tx, ty)) = parse_root_adt_filename(&path) else {
            skipped += 1;
            continue;
        };

        // Optional: ensure the filename map matches the continent_name loosely (case-insensitive)
        // If you want strict matching, uncomment:
        // if map_name.to_ascii_lowercase() != continent_name.to_ascii_lowercase() { continue; }

        match parse_adt_areaids(&path) {
            Ok(Some(area_ids)) => {
                let b64 = encode_tile_deflate_b64(&area_ids)?;
                let key = tile_key(tx, ty);
                export.tiles.insert(key, b64);
                parsed += 1;
                if parsed % 100 == 0 {
                    println!("  parsed {} tiles...", parsed);
                }
            }
            Ok(None) => {
                // Truly empty tile (0 chunks), skip
                println!("  SKIPPED (0 chunks): {}_{}_{}",  map_name, tx, ty);
                skipped += 1;
            }
            Err(e) => {
                eprintln!("  ERROR parsing {}: {}", path.display(), e);
                errors += 1;
            }
        }
    }

    println!(
        "Done. parsed={} skipped(non-root)={} errors={}",
        parsed, skipped, errors
    );
    println!("Export tiles: {}", export.tiles.len());

    Ok(export)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 3 {
        println!("Usage: {} <adt_directory> <continent_name>", args[0]);
        println!("Example: {} ./kalimdor_adts Kalimdor", args[0]);
        println!("This only processes root ADTs named like: kalimdor_X_Y.adt (skips _obj/_tex/_lod).");
        return Ok(());
    }

    let adt_dir = PathBuf::from(&args[1]);
    let continent_name = &args[2];

    let export = build_tile_export(&adt_dir, continent_name)?;
    let out_path = format!("{}_tiles.lua", continent_name);
    export.export_lua(Path::new(&out_path))?;

    println!("Wrote: {}", out_path);
    Ok(())
}